steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'us-central1-docker.pkg.dev/$PROJECT_ID/kevin224860/GCP-Assignment2:${SHORT_SHA}', '.']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'us-central1-docker.pkg.dev/$PROJECT_ID/kevin224860/GCP-Assignment2:${SHORT_SHA}']

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'GCP-Assignment2-service'  # Replace with your Cloud Run service name
      - '--image'
      - 'us-central1-docker.pkg.dev/$PROJECT_ID/kevin224860/GCP-Assignment2:${SHORT_SHA}'
      - '--region'
      - 'us-central1'

images:
  - 'us-central1-docker.pkg.dev/$PROJECT_ID/kevin224860/GCP-Assignment2:${SHORT_SHA}'

options:
  defaultLogsBucketBehavior: REGIONAL_USER_OWNED_BUCKET

triggers:
- name: gcp-assignment2-trigger
  github:
    push:
      branch: 'main'  # Or your branch name
  approval:
    required: true