services:
  server:
    build:
      context: .
    environment:
      NODE_ENV: production
      PORT: 3000  # Ensure the application reads this port
    ports:
      - 3000:3000  # Map container port 8080 to host port 8080
