services:
  server:
    build:
      context: .
    environment:
      NODE_ENV: production
      PORT: 8080  # Ensure the application reads this port
    ports:
      - 8080:8080  # Map container port 8080 to host port 8080
